name: Hello World Docker Action
description: A simple action that greets someone using a Docker container

inputs:
  who-to-greet:
    description: The name to greet
    required: false
    default: 'World'

outputs:
  time:
    description: The time when the greeting was printed

runs:
  using: 'docker'
  image: 'docker://hello-world'
